<a href="https://colab.research.google.com/github/SandhuruT/Data_Science_01/blob/main/My_Data_Science_Work_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:


print("========Simple Calculater==========")
print("====Operations +,-,*,/,**,//,% ====")
print("===================================")

# Step 1: Get inputs

num1 = float(input("Enter first number: "))
operater = input("Enter the operater (+,-,*,/,**,//,%):" )
num2 = float(input("Enter second number: "))

# Step 2: Perform calculation
if operater == "+":
  result = num1 + num2
elif operater == "-":
  result = num1 - num2
elif operater == "**":
  result = num1 ** num2
elif operater == "//":
  if num2 == 0:
    print("Error: Division by zero")
  else:
    result = num1 // num2
elif operater == "*":
  result = num1 * num2
elif operater == "/":
  if num2 == 0:
    print("Error: Division by zero")
  else:
    result = num1 / num2
elif operater == "%":
  result = num1 * num2

else:
    result = "Invalid operator!"

# Step 3: Show result
print(f"\nHistory of the last calculation: {num1} {operater} {num2} = {result}")
print("===================================")

========Simple Calculater==========
====Operations +,-,*,/,**,//,% ====
Enter first number: 5
Enter the operater (+,-,*,/,**,//,%):*
Enter second number: 5

History of the last calculation: 5.0 * 5.0 = 25.0


In [ ]:
import random

def generate_secret(min_value, max_value):
  return random.randint(min_value, max_value)

def check_guess(secret, guess):
  """Check if guess is correct, too high, or too low"""
  if guess == secret:
      return "correct"
  elif guess < secret:
      return "too_low"
  else:
      return "too_high"


# main
def main():
  print("=" * 35)
  print("    NUMBER GUESSING GAME ")
  print("=" * 35)

  # condition

  min_value = 1
  max_value = 100
  max_attempts = 7

  # secret number
  secret = generate_secret(min_value, max_value)
  attempts = 0
  game_won = False

  print(f"I'm thinking of a number between {min_value} and {max_value}")
  print(f"You have {max_attempts} attempts. Good luck!\n")
  while attempts < max_attempts:
    attempts += 1
    remaining = max_attempts - attempts

# get player guess
    try:
      guess = int(input(f"Attempt {attempts}/{max_attempts} — Your guess: "))
    except ValueError:
      print("⚠️  Please enter a valid number!\n")
      attempts -= 1
      continue

# check the guess
    result = check_guess(secret, guess)

    if result == "correct":
      game_won = True
      break
    elif result == "too_low":
      print("⚠️  Too low!\n")
    else:
      print("⚠️  Too high!\n")


    if remaining > 0:
      print(f"You have {remaining} attempts remaining.\n")

# show result
  print ("=" * 35)

  if game_won:
    print("Congratulations! You guessed the secret number!")

    if attempts <= 3:
      print('Amazing! yours a genius')
    elif attempts <=5:
      print("Great job")
    else:
      print("you win")
  else:
    print("Game over! You ran out of attempts.")
    print(f"The number was {secret}")


  game_won == False
  if input("Do you want to play again? (yes/no): ").lower() == "yes":
    main()
  else:
    print("Thanks for playing! Goodbye!")
    game_won == True

main()


    NUMBER GUESSING GAME 
I'm thinking of a number between 1 and 100
You have 7 attempts. Good luck!

Attempt 1/7 — Your guess: 50
⚠️  Too low!

You have 6 attempts remaining.

Attempt 2/7 — Your guess: 85
⚠️  Too high!

You have 5 attempts remaining.

Attempt 3/7 — Your guess: 65
⚠️  Too low!

You have 4 attempts remaining.

Attempt 4/7 — Your guess: 75
⚠️  Too high!

You have 3 attempts remaining.

Attempt 5/7 — Your guess: 70
⚠️  Too low!

You have 2 attempts remaining.

Attempt 6/7 — Your guess: 77
⚠️  Too high!

You have 1 attempts remaining.

Attempt 7/7 — Your guess: 76
⚠️  Too high!

Game over! You ran out of attempts.
The number was 73
Do you want to play again? (yes/no): yes
    NUMBER GUESSING GAME 
I'm thinking of a number between 1 and 100
You have 7 attempts. Good luck!

Attempt 1/7 — Your guess: 50
⚠️  Too high!

You have 6 attempts remaining.

Attempt 2/7 — Your guess: 25
⚠️  Too high!

You have 5 attempts remaining.

Attempt 3/7 — Your guess: 10
⚠️  Too high!

You have

In [1]:
# =============================================
# PROJECT: Student Grade Tracker System
# =============================================

def calculate_average(scores):
    """Calculate average of a list of scores"""
    if len(scores) == 0:
        return 0
    return sum(scores) / len(scores)

def assign_grade(average):
    """Assign letter grade based on average"""
    if average >= 90:
        return "A+"
    elif average >= 80:
        return "A"
    elif average >= 70:
        return "B"
    elif average >= 60:
        return "C"
    else:
        return "F"

def create_student(name, scores):
    """Create a student dictionary"""
    avg   = calculate_average(scores)
    grade = assign_grade(avg)
    return {
        "name"    : name,
        "scores"  : scores,
        "average" : round(avg, 2),
        "grade"   : grade,
        "highest" : max(scores),
        "lowest"  : min(scores)
    }

def display_student(student):
    """Display one student's report"""
    print(f"\n  Student : {student['name']}")
    print(f"  Scores  : {student['scores']}")
    print(f"  Average : {student['average']}")
    print(f"  Grade   : {student['grade']}")
    print(f"  Highest : {student['highest']}")
    print(f"  Lowest  : {student['lowest']}")

def display_class_report(students):
    """Display full class analysis"""
    print("\n" + "=" * 45)
    print("          CLASS REPORT CARD ")
    print("=" * 45)

    for student in students:
        display_student(student)
        print("  " + "-" * 35)

    # Class statistics
    all_averages = [s["average"] for s in students]
    all_grades   = [s["grade"] for s in students]

    print("\n CLASS STATISTICS")
    print("-" * 35)
    print(f"  Total Students  : {len(students)}")
    print(f"  Class Average   : {calculate_average(all_averages):.2f}")
    print(f"  Highest Average : {max(all_averages)}")
    print(f"  Lowest Average  : {min(all_averages)}")

    # Grade distribution
    print("\n🏆 GRADE DISTRIBUTION")
    print("-" * 35)
    unique_grades = sorted(set(all_grades))
    for grade in unique_grades:
        count    = all_grades.count(grade)
        students_with_grade = [s["name"] for s in students
                               if s["grade"] == grade]
        print(f"  Grade {grade}: {count} student(s)"
              f" → {students_with_grade}")

    # Top performers
    top = [s for s in students if s["average"] >= 80]
    print(f"\n TOP PERFORMERS (avg ≥ 80): "
          f"{[s['name'] for s in top]}")

    # Students needing help
    struggling = [s for s in students if s["average"] < 60]
    if struggling:
        print(f"  NEEDS SUPPORT: "
              f"{[s['name'] for s in struggling]}")
    else:
        print(" No students failing!")


# ── Main Program ──────────────────────────────

# Student data (name, list of 5 subject scores)
data = [
    ("Alice",   [92, 88, 95, 91, 87]),
    ("Bob",     [78, 82, 75, 80, 85]),
    ("Charlie", [65, 70, 60, 68, 72]),
    ("Diana",   [95, 98, 92, 96, 99]),
    ("Eve",     [55, 48, 62, 51, 58]),
    ("Frank",   [88, 84, 90, 86, 83]),
]

# Create student records
classroom = []
for name, scores in data:
    student = create_student(name, scores)
    classroom.append(student)

# Display full report
display_class_report(classroom)


          CLASS REPORT CARD 

  Student : Alice
  Scores  : [92, 88, 95, 91, 87]
  Average : 90.6
  Grade   : A+
  Highest : 95
  Lowest  : 87
  -----------------------------------

  Student : Bob
  Scores  : [78, 82, 75, 80, 85]
  Average : 80.0
  Grade   : A
  Highest : 85
  Lowest  : 75
  -----------------------------------

  Student : Charlie
  Scores  : [65, 70, 60, 68, 72]
  Average : 67.0
  Grade   : C
  Highest : 72
  Lowest  : 60
  -----------------------------------

  Student : Diana
  Scores  : [95, 98, 92, 96, 99]
  Average : 96.0
  Grade   : A+
  Highest : 99
  Lowest  : 92
  -----------------------------------

  Student : Eve
  Scores  : [55, 48, 62, 51, 58]
  Average : 54.8
  Grade   : F
  Highest : 62
  Lowest  : 48
  -----------------------------------

  Student : Frank
  Scores  : [88, 84, 90, 86, 83]
  Average : 86.2
  Grade   : A
  Highest : 90
  Lowest  : 83
  -----------------------------------

 CLASS STATISTICS
-----------------------------------
  Total S

In [2]:
# =====================================================
# PROJECT:  Sales Data Analyzer
# =====================================================
import csv
import json
from datetime import datetime

def create_sales_data():
    """Create sample sales CSV"""
    sales = """date,product,category,quantity,price,city
2024-01-05,Laptop,Electronics,2,75000,Mumbai
2024-01-07,Phone,Electronics,5,25000,Delhi
2024-01-08,Desk,Furniture,3,12000,Bangalore
2024-01-10,Laptop,Electronics,1,75000,Mumbai
2024-01-12,Chair,Furniture,8,5000,Delhi
2024-01-15,Tablet,Electronics,4,35000,Chennai
2024-01-18,Phone,Electronics,6,25000,Bangalore
2024-01-20,Sofa,Furniture,2,45000,Mumbai
2024-01-22,Laptop,Electronics,3,75000,Delhi
2024-01-25,Tablet,Electronics,2,35000,Mumbai
2024-01-28,Chair,Furniture,5,5000,Chennai
2024-01-30,Phone,Electronics,3,25000,Delhi
"""
    with open("sales.csv", "w") as f:
        f.write(sales)
    print(" sales.csv created!\n")


def load_sales(filename):
    """Load and process sales data"""
    sales = []
    try:
        with open(filename, "r") as file:
            reader = csv.DictReader(file)
            for row in reader:
                sales.append({
                    "date"    : row["date"],
                    "product" : row["product"],
                    "category": row["category"],
                    "quantity": int(row["quantity"]),
                    "price"   : int(row["price"]),
                    "city"    : row["city"],
                    "revenue" : int(row["quantity"]) * int(row["price"])
                })
    except FileNotFoundError:
        print(" sales.csv not found!")
        return []
    return sales


def sales_summary(sales):
    """Overall summary"""
    total_revenue  = sum(s["revenue"] for s in sales)
    total_quantity = sum(s["quantity"] for s in sales)
    total_orders   = len(sales)
    avg_order      = total_revenue // total_orders

    print("=" * 45)
    print("        SALES ANALYSIS REPORT")
    print("=" * 45)
    print(f"  Total Orders   : {total_orders}")
    print(f"  Items Sold     : {total_quantity}")
    print(f"  Total Revenue  : ₹{total_revenue:,}")
    print(f"  Avg Order Value: ₹{avg_order:,}")


def revenue_by_category(sales):
    """Revenue per category"""
    categories = {}
    for s in sales:
        cat = s["category"]
        categories[cat] = categories.get(cat, 0) + s["revenue"]

    print("\n REVENUE BY CATEGORY")
    print("-" * 35)
    for cat, rev in sorted(categories.items(),
                           key=lambda x: x[1], reverse=True):
        print(f"  {cat:15} : ₹{rev:,}")


def top_products(sales):
    """Best selling products by revenue"""
    products = {}
    for s in sales:
        p = s["product"]
        if p not in products:
            products[p] = {"revenue": 0, "quantity": 0}
        products[p]["revenue"]  += s["revenue"]
        products[p]["quantity"] += s["quantity"]

    print("\n TOP PRODUCTS BY REVENUE")
    print("-" * 40)
    sorted_products = sorted(products.items(),
                             key=lambda x: x[1]["revenue"],
                             reverse=True)
    for product, info in sorted_products:
        print(f"  {product:8} | "
              f"Revenue: ₹{info['revenue']:>10,} | "
              f"Qty: {info['quantity']}")


def revenue_by_city(sales):
    """City-wise performance"""
    cities = {}
    for s in sales:
        c = s["city"]
        cities[c] = cities.get(c, 0) + s["revenue"]

    print("\n  REVENUE BY CITY")
    print("-" * 35)
    max_rev = max(cities.values())
    for city, rev in sorted(cities.items(),
                            key=lambda x: x[1], reverse=True):
        bar_len = int((rev / max_rev) * 15)
        bar = "█" * bar_len
        print(f"  {city:12} | {bar:<15} ₹{rev:,}")


def save_report(sales):
    """Save analysis to JSON"""
    total_rev = sum(s["revenue"] for s in sales)
    report = {
        "generated_on"  : str(datetime.now()),
        "total_orders"  : len(sales),
        "total_revenue" : total_rev,
        "top_product"   : max(sales, key=lambda x: x["revenue"])["product"]
    }
    with open("sales_report.json", "w") as f:
        json.dump(report, f, indent=4)
    print("\n Report saved to sales_report.json!")


# ── Run Everything ──────────────────────────────
create_sales_data()
sales = load_sales("sales.csv")

if sales:
    sales_summary(sales)
    revenue_by_category(sales)
    top_products(sales)
    revenue_by_city(sales)
    save_report(sales)

 sales.csv created!

        SALES ANALYSIS REPORT
  Total Orders   : 12
  Items Sold     : 44
  Total Revenue  : ₹1,201,000
  Avg Order Value: ₹100,083

 REVENUE BY CATEGORY
-----------------------------------
  Electronics     : ₹1,010,000
  Furniture       : ₹191,000

 TOP PRODUCTS BY REVENUE
----------------------------------------
  Laptop   | Revenue: ₹   450,000 | Qty: 6
  Phone    | Revenue: ₹   350,000 | Qty: 14
  Tablet   | Revenue: ₹   210,000 | Qty: 6
  Sofa     | Revenue: ₹    90,000 | Qty: 2
  Chair    | Revenue: ₹    65,000 | Qty: 13
  Desk     | Revenue: ₹    36,000 | Qty: 3

  REVENUE BY CITY
-----------------------------------
  Delhi        | ███████████████ ₹465,000
  Mumbai       | ████████████    ₹385,000
  Bangalore    | ██████          ₹186,000
  Chennai      | █████           ₹165,000

 Report saved to sales_report.json!


In [4]:
# =====================================================
# PROJECT: NumPy Matrix Calculator & Data Analyzer
# =====================================================
import numpy as np

np.random.seed(42)

# ── PART 1: Matrix Calculator ─────────────────────────
def matrix_calculator():
    print("=" * 50)
    print("      MATRIX CALCULATOR")
    print("=" * 50)

    A = np.array([[2, 3, 1],
                  [4, 1, 5],
                  [3, 2, 4]])

    B = np.array([[1, 2, 3],
                  [5, 4, 2],
                  [1, 3, 4]])

    print(f"\nMatrix A:\n{A}")
    print(f"\nMatrix B:\n{B}")

    print(f"\nA + B:\n{A + B}")
    print(f"\nA - B:\n{A - B}")
    print(f"\nA * B (element-wise):\n{A * B}")
    print(f"\nA @ B (dot product):\n{A @ B}")
    print(f"\nTranspose of A:\n{A.T}")
    print(f"\nDeterminant of A : {np.linalg.det(A):.2f}")
    print(f"\nInverse of A:\n{np.round(np.linalg.inv(A), 3)}")

    eigenvalues, eigenvectors = np.linalg.eig(A)
    print(f"\nEigenvalues : {np.round(eigenvalues, 3)}")

# ── PART 2: Student Performance Analyzer ─────────────
def student_analyzer():
    print("\n" + "=" * 50)
    print("      STUDENT PERFORMANCE ANALYZER")
    print("=" * 50)

    subjects = ["Math", "Science", "English",
                "History", "CS"]
    students = ["Alice", "Bob", "Charlie",
                "Diana", "Eve", "Frank"]

    # Generate random scores (60-100)
    scores = np.random.randint(60, 101,
                               size=(6, 5))

    print("\nRAW SCORES")
    print(f"{'':10}", end="")
    for sub in subjects:
        print(f"{sub:10}", end="")
    print()
    print("-" * 60)

    for i, student in enumerate(students):
        print(f"{student:10}", end="")
        for score in scores[i]:
            print(f"{score:<10}", end="")
        print()

    # Student averages (axis=1 = across columns)
    student_avg = np.mean(scores, axis=1)

    # Subject averages (axis=0 = down rows)
    subject_avg = np.mean(scores, axis=0)

    print(f"\n STUDENT AVERAGES")
    print("-" * 35)
    sorted_idx = np.argsort(student_avg)[::-1]
    for rank, i in enumerate(sorted_idx, 1):
        bar_len = int(student_avg[i] / 5)
        bar = "█" * bar_len
        print(f"  {rank}. {students[i]:8} | "
              f"{bar:<20} | "
              f"{student_avg[i]:.1f}")

    print(f"\n SUBJECT AVERAGES")
    print("-" * 35)
    for sub, avg in zip(subjects, subject_avg):
        bar_len = int(avg / 5)
        bar = "█" * bar_len
        status = "✅" if avg >= 75 else "⚠️"
        print(f"  {sub:10} | {bar:<20} | "
              f"{avg:.1f} {status}")

    # Class statistics
    print(f"\n CLASS STATISTICS")
    print("-" * 35)
    print(f"  Highest score  : {np.max(scores)}"
          f" ({students[np.argmax(scores)//5]})")
    print(f"  Lowest score   : {np.min(scores)}"
          f" ({students[np.argmin(scores)//5]})")
    print(f"  Class average  : {np.mean(scores):.2f}")
    print(f"  Std deviation  : {np.std(scores):.2f}")

    # Pass/fail analysis
    passing = np.sum(scores >= 70)
    total   = scores.size
    print(f"  Pass rate      : "
          f"{passing}/{total} = "
          f"{passing/total*100:.1f}%")

    # Normalize scores
    normalized = (scores - scores.min()) / \
                 (scores.max() - scores.min())

    print(f"\n TOP PERFORMERS (avg ≥ 80)")
    print("-" * 35)
    top = [(students[i], student_avg[i])
           for i in range(len(students))
           if student_avg[i] >= 80]
    for name, avg in sorted(top,
                            key=lambda x: x[1],
                            reverse=True):
        print(f"   {name:10} : {avg:.1f}")


# ── Run Project ───────────────────────────────────────
matrix_calculator()
student_analyzer()

      MATRIX CALCULATOR

Matrix A:
[[2 3 1]
 [4 1 5]
 [3 2 4]]

Matrix B:
[[1 2 3]
 [5 4 2]
 [1 3 4]]

A + B:
[[3 5 4]
 [9 5 7]
 [4 5 8]]

A - B:
[[ 1  1 -2]
 [-1 -3  3]
 [ 2 -1  0]]

A * B (element-wise):
[[ 2  6  3]
 [20  4 10]
 [ 3  6 16]]

A @ B (dot product):
[[18 19 16]
 [14 27 34]
 [17 26 29]]

Transpose of A:
[[2 4 3]
 [3 1 2]
 [1 5 4]]

Determinant of A : -10.00

Inverse of A:
[[ 0.6  1.  -1.4]
 [ 0.1 -0.5  0.6]
 [-0.5 -0.5  1. ]]

Eigenvalues : [ 8.194  0.659 -1.852]

      STUDENT PERFORMANCE ANALYZER

RAW SCORES
          Math      Science   English   History   CS        
------------------------------------------------------------
Alice     98        88        74        67        80        
Bob       98        78        82        70        70        
Charlie   83        95        99        83        62        
Diana     81        61        83        89        97        
Eve       61        80        92        71        81        
Frank     84        86        87        75 